biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

biblioteca/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro', views.cadastro, name='cadastro'),
    path('listar', views.listar, name='listar'),
    path('deletar', views.deletar, name='deletar'),
    path('atualizar', views.atualizar, name='atualizar')
]

biblioteca/core/models.py
from django.db import models

class LivroModel(models.Model):

    titulo = models.CharField('Título', max_length=200)
    editora = models.CharField('Editora', max_length=200)
    autor = models.CharField('Autor', max_length=200)
    isbn = models.PositiveIntegerField('ISBN', unique=True)  
    numero_paginas = models.PositiveIntegerField('Número de Páginas')  
    ano_escrita = models.PositiveSmallIntegerField('Ano da Obra')  

    def __str__(self):
        return self.titulo

biblioteca/core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from core.models import LivroModel
from datetime import datetime


    
def validate_titulo(value):
    if len(value) < 3:
        raise ValidationError('título deve ter pelo menos três caracteres')
    
def validate_editora(value):
    if len(value) < 3:
        raise ValidationError('editora deve ter pelo menos três caracteres')
    
def validate_autor(value):
    if len(value) < 10:
        raise ValidationError('Autor deve ter pelo menos 10 caracteres')
    
def validate_isbn(value):
    if value < 1000000000000 or value > 9999999999999:
        raise ValidationError('O ISBN deve ter exatamente 13 dígitos')

def validate_numero_paginas(value):
    if value < 1 or value > 999:
        raise ValidationError('O número de páginas deve ser um valor entre 1 e 999')

def validate_ano_escrita(value):
    if value < 1000 or value > 9999:
        raise ValidationError('O ano da obra deve conter exatamente 4 dígitos numéricos')

    current_year = datetime.now().year
    if int(value) > current_year:
        raise ValidationError('O ano de escrita não pode ser posterior ao ano atual')




class LivroForm(forms.ModelForm):
    class Meta:
        model = LivroModel
        fields = ['titulo', 'editora', 'autor', 'isbn', 'numero_paginas', 'ano_escrita']
        error_messages = {
            'titulo': {
                'required': ("Informe o título do livro."),
            },
            'editora': {
                'required': ("Informe a editora do livro."),
            },
            'autor': {
                'required': ("Informe o autor do livro."),
            },
            'isbn': {
                'required': ("Informe o ISBN do livro."),
            },
            'numero_paginas': {
                'required': ("Informe o número de páginas do livro."),
            },
            'ano_escrita': {
                'required': ("Informe o ano de escrita do livro."),
            },
        }

    def clean_titulo(self):
        titulo = self.cleaned_data['titulo']
        validate_titulo(titulo)
        return titulo

    def clean_editora(self):
        editora = self.cleaned_data['editora']
        validate_editora(editora)
        return editora

    def clean_autor(self):
        autor = self.cleaned_data['autor']
        validate_autor(autor)
        return autor

    def clean_isbn(self):
        isbn = self.cleaned_data['isbn']
        validate_isbn(isbn)
        return isbn

    def clean_numero_paginas(self):
        numero_paginas = self.cleaned_data['numero_paginas']
        validate_numero_paginas(numero_paginas)
        return numero_paginas

    def clean_ano_escrita(self):
        ano_escrita = self.cleaned_data['ano_escrita']
        validate_ano_escrita(ano_escrita)
        return ano_escrita

    def clean(self):
        self.cleaned_data = super().clean()
        return self.cleaned_data

biblioteca/core/views.py
from django.shortcuts import redirect, render, HttpResponseRedirect
from django.urls import reverse
from .forms import LivroForm
from .models import LivroModel
from django.shortcuts import get_object_or_404

def index(request):
    if request.method == 'GET':
        return render(request, "index.html")
    else:
        return HttpResponseRedirect(reverse('core:index'))

def cadastro(request):
    if request.method == 'POST':
        form_livro = LivroForm(request.POST)
        if form_livro.is_valid():
            eleitor = LivroModel.objects.create(**form_livro.cleaned_data)
            return HttpResponseRedirect(reverse('core:index'))  
        else:
            contexto = {'formulario_livro': form_livro}
            return render(request, "cadastro.html", contexto)
    else:
        contexto = {'formulario_livro': LivroForm()}
        return render(request, 'cadastro.html', contexto)

def listar(request):
    if request.method == 'POST':
        livro_id = request.POST.get('livro_id', '')
        try:
            livro = LivroModel.objects.get(pk=livro_id)
            contexto = {'livro': livro}
        except ValueError:
            contexto = {}
        return render(request, "detalhes.html", contexto)
    else:
        livros = LivroModel.objects.all()
        contexto = {'livros': livros}
        return render(request, 'listar.html', contexto)

def deletar(request):
    if request.method == 'POST':
        livro_id = request.POST.get('livro_id')
        livro = LivroModel.objects.get(pk=livro_id)
        livro.delete()
        return render(request, 'index.html')

def atualizar(request):
    if request.method == 'POST':
        livro_id = request.POST.get('livro_id')
        livro = LivroModel.objects.get(pk=livro_id)
        form_livro = LivroForm(request.POST, instance=livro)
        if form_livro.is_valid():
            form_livro.save()
            return HttpResponseRedirect(reverse('core:index'))
        else:
            contexto = {'formulario_livro': form_livro}
            return render(request, "atualizar.html", contexto)      
    else: 
        contexto = {'formulario_livro': LivroForm()}
        return render(request, 'atualizar.html', contexto)

biblioteca/core/templates/atualizar.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
        <link rel="icon" type="image/x-icon" href="{% static 'css/logo.png' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>Library Tech</title>
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="http://127.0.0.1:8000/">
                <img src="{% static 'css/logo.png' %}" alt="Logo" class="logo" style="height: 40px;">
                LibraryTech
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:8000/admin">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="dev.html">Desenvolvedores</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
        <br>
<div class="container mt-5">
    <h1 class="mb-4">Atualização de Livros</h1>

    <div class="card shadow">
        <div class="card-body">
            <form action="{% url 'core:atualizar' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_titulo" class="form-label">Título:</label>
                    {{ formulario_livro.titulo }}
                </div>
                <div class="mb-3">
                    <label for="id_editora" class="form-label">Editora:</label>
                    {{ formulario_livro.editora }}
                </div>
                <div class="mb-3">
                    <label for="id_autor" class="form-label">Autor:</label>
                    {{ formulario_livro.autor }}
                </div>
                <div class="mb-3">
                    <label for="id_isbn" class="form-label">ISBN:</label>
                    {{ formulario_livro.isbn }}
                </div>
                <div class="mb-3">
                    <label for="id_numero_paginas" class="form-label">Número de Páginas:</label>
                    {{ formulario_livro.numero_paginas }}
                </div>
                <div class="mb-3">
                    <label for="id_ano_escrita" class="form-label">Ano de Escrita:</label>
                    {{ formulario_livro.ano_escrita }}
                </div>
                <button type="submit" class="btn btn-primary">Atualizar</button>
            </form>

            {% if formulario_livro.errors %}
                <div class="alert alert-danger mt-3" role="alert">
                    {% for field in formulario_livro %}
                        {% for error in field.errors %}
                            <strong>{{ error|escape }}</strong><br>
                        {% endfor %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>

    <form action="{% url 'core:listar' %}" method="GET">
        <button type="submit" class="btn btn-secondary mt-3">Voltar</button>              
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

biblioteca/core/templates/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Library Tech</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet"> 
    <link rel="icon" type="image/x-icon" href="{% static 'css/logo.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body style="background-color: #e8ddcb;">
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="http://127.0.0.1:8000/">
                <img src="{% static 'css/logo.png' %}" alt="Logo" class="logo" style="height: 40px;">
                LibraryTech
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:8000/admin">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="dev.html">Desenvolvedores</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="text-center">
            <h1 class="mt-5 mb-4">Cadastro de livros</h1>
        </div>
    <div class="container mt-5">
        <div class="card shadow">
            <div class="card-body">                
                <form action="{% url 'core:cadastro' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_titulo" class="form-label">Título:</label>
                        {{ formulario_livro.titulo }}
                    </div>
                    <div class="mb-3">
                        <label for="id_editora" class="form-label">Editora:</label>
                        {{ formulario_livro.editora }}
                    </div>
                    <div class="mb-3">
                        <label for="id_autor" class="form-label">Autor:</label>
                        {{ formulario_livro.autor }}
                    </div>
                    <div class="mb-3">
                        <label for="id_isbn" class="form-label">ISBN:</label>
                        {{ formulario_livro.isbn }}
                    </div>
                    <div class="mb-3">
                        <label for="id_numero_paginas" class="form-label">Número de Páginas:</label>
                        {{ formulario_livro.numero_paginas }}
                    </div>
                    <div class="mb-3">
                        <label for="id_ano_escrita" class="form-label">Ano de Escrita:</label>
                        {{ formulario_livro.ano_escrita }}
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Cadastrar</button>
                    </div>
                </form>

                {% if formulario_livro.errors %}
                    <div class="alert alert-danger mt-3" role="alert">
                        {% for field in formulario_livro %}
                            {% for error in field.errors %}
                                <strong>{{ error|escape }}</strong><br>
                            {% endfor %}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <form action="{% url 'core:index' %}" method="GET">
            <div class="text-center mt-3">
                <button type="submit" class="btn btn-secondary">Voltar</button>
            </div>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

biblioteca/core/templates/detalhes.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet"> <!-- Importando a fonte Roboto -->
        <link rel="icon" type="image/x-icon" href="{% static 'css/logo.png' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>Library Tech</title>
    </head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="http://127.0.0.1:8000/">
                <img src="{% static 'css/logo.png' %}" alt="Logo" class="logo" style="height: 40px;">
                LibraryTech
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:8000/admin">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="dev.html">Desenvolvedores</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Conteúdo Principal -->
    <div class="container">
        <div class="text-center">
            <h1 class="mt-5 mb-4">Detalhes do livro</h1>
        </div>
        {% if livro %}
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-body">
                            <div class="mt-4">
                                <h3>
                                    ID: {{ livro.id }}
                                    <br><br>
                                    Livro: {{ livro.titulo }}
                                    <br><br>
                                    Editora: {{ livro.editora }}
                                    <br><br>
                                    Autor: {{ livro.autor }}
                                    <br><br>
                                    ISBN: {{ livro.isbn }}
                                    <br><br>
                                    Número de Páginas: {{ livro.numero_paginas }}
                                    <br><br>
                                    Ano de Escrita: {{ livro.ano_escrita }}
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="text-center mt-5">
                <h2>Nenhum livro cadastrado</h2>
            </div>
        {% endif %}

        <div class="text-center mt-4">
            <form action="{% url 'core:listar' %}" novalidate method="GET">
                <button type="submit" class="btn btn-primary">Voltar</button>              
            </form>
        </div>
    </div>

    <!-- Scripts Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-f0yV4T+v5Vjg7CGJtyidvF3ZROeMkaBiYIhoBfFv5hFvr81s/xw1wJgS1Jm3a5Dp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></script>
</body>
</html>

biblioteca/core/templates/dev.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'css/logo.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Library Tech</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="http://127.0.0.1:8000/">
                <img src="{% static 'css/logo.png' %}" alt="Logo" class="logo" style="height: 40px;">
                LibraryTech
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:8000/admin">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="dev.html">Desenvolvedores</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    teste

</body>

biblioteca/core/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'css/logo.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Library Tech</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="http://127.0.0.1:8000/">
                <img src="{% static 'css/logo.png' %}" alt="Logo" class="logo" style="height: 40px;">
                LibraryTech
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:8000/admin">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="dev.html">Desenvolvedores</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-5 mb-4">
        <div class="text-center">
            <h2>Este sistema permite o cadastro de livros utilizados como referência bibliográfica em faculdades.</h2>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5 mb-3">
                <div class="card h-100">
                    <img src="{% static 'css/livros-pilha.jpg' %}" class="card-img-top" alt="Livros">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Listar livros</h5>
                        <p class="card-text">Dentro de nosso banco de dados temos milhares de livros que são referências bibliográficas usadas no meio acadêmico para auxiliar o estudo. Listando os livros cadastrados voce poderá: </p>
                        <ul class="list-group list-group-flush mb-3">
                            <li class="list-group-item">Detalhes da obra</li>
                            <li class="list-group-item">Possibilidade de excluir o livro</li>
                            <li class="list-group-item">Ferramenta de edição do registro</li>
                        </ul>
                        <form action="{% url 'core:listar' %}" novalidate method="GET" class="mt-auto">
                            <input type="submit" class="btn btn-custom" value="Listar"/>              
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-md-5 mb-3">
                <div class="card h-100">
                    <img src="{% static 'css/livros-cad.jpg' %}" class="card-img-top" alt="Livros">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Cadastrar Novo</h5>
                        <p class="card-text">Cadastrar suas referências bibliográficas é fundamental para garantir a credibilidade e a integridade de seus trabalhos acadêmicos e científicos. Ao registrar corretamente cada obra consultada, você:</p>
                        <ul class="list-group list-group-flush mb-3">
                            <li class="list-group-item">Garante a integridade do seu trabalho</li>
                            <li class="list-group-item">Facilita a organização das suas fontes</li>
                            <li class="list-group-item">Melhora a qualidade acadêmica</li>
                        </ul>
                        <form action="{% url 'core:cadastro' %}" novalidate method="GET" class="mt-auto">
                            <input type="submit" class="btn btn-custom" value="Cadastrar"/>              
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

biblioteca/core/templates/listar.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet"> 
        <link rel="icon" type="image/x-icon" href="{% static 'css/logo.png' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>Library Tech</title>
    </head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="http://127.0.0.1:8000/">
                <img src="{% static 'css/logo.png' %}" alt="Logo" class="logo" style="height: 40px;">
                LibraryTech
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:8000/admin">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="dev.html">Desenvolvedores</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-5 mb-4">
        <div class="text-center mb-4">
            <h2>Colecão de bibliografias</h2>
        </div>

        {% if livros %}
            <div class="list-group">
                {% for livro in livros %}
                    <div class="list-group-item list-group-item-action">
                        <h5 class="mb-1">Livro: {{ livro }}</h5>
                        <div class="d-flex justify-content-between">
                            <form action={% url 'core:listar' %} method="POST" class="d-inline-block">
                                {% csrf_token %}
                                <input type="hidden" name="livro_id" value="{{ livro.pk }}">
                                <input type="submit" class="btn btn-primary btn-sm" value="Detalhes"/>
                            </form>
                            <form action={% url 'core:deletar' %} method="POST" class="d-inline-block">
                                {% csrf_token %}
                                <input type="hidden" name="livro_id" value="{{ livro.pk }}">
                                <input type="submit" class="btn btn-danger btn-sm" value="Deletar"/>
                            </form>
                            <form action={% url 'core:atualizar' %} method="POST" class="d-inline-block">
                                {% csrf_token %}
                                <input type="hidden" name="livro_id" value="{{ livro.pk }}">
                                <input type="submit" class="btn btn-warning btn-sm" value="Atualizar"/>
                            </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="alert alert-info" role="alert">
                Nenhum livro cadastrado.
            </div>
        {% endif %}

        <div class="text-center mt-4">
            <form action={% url 'core:index' %} method="GET">
                <input type="submit" class="btn btn-secondary" value="Voltar"/>
            </form>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>